url-shortener:
  base-url: https://pre.commons.kapitalbank.az/api
  short-url-path: /v1/url-shortener/public/
  static-tokens:
    - bb: https://birbank.az
    - bc: https://birkart.az
    - bk: https://birkart.az